### ISSUE TITLE
Can't detect clients.

### ISSUE THREAD

**Issue by RG2N** [Sportkanone123/ClientDetector#1]
Plugin simply returns "Vanilla or undetectable client." while other plugins get the client name correct every time.

**Comment by Sportkanone123** [comment]
Hey, can you give me some more information like:
1. Plugin version, server version, server software
2. Did you use the ingame notifications or the Developer API?
3. What clients did you test?
That would help a lot to fix the issue. 
~Sportkanone123

**Comment by RG2N** [comment]
The plugin version is the latest on the spigotmc, I just used the command /clientdetector player client <player> and it said unknown.  I made my own client called "PolarClient" and it works with other plugins but not yours.

**Comment by Sportkanone123** [comment]
Yes, I have discord, my tag is Sportkanone123#8911, you can contact me privately on discord or join my discord server (https://discord.gg/gwsSTykWbu).
The problem is that I have to add every client manually to the plugin (de.sportkanone123.clientdetector.spigot.manager.ClientManager.java) that’s why your client isn’t detected. If you tell me what you changed (data send on “minecraft:brand” or your custom channel) so that the other plugins detect your client I can add it to the clients list. Another option would be that you send me your client and I test it manually and see if it’s detectable.
~Sportkanone123

**Comment by AdminHcat** [comment]
> Yes, I have discord, my tag is Sportkanone123#8911, you can contact me privately on discord or join my discord server (https://discord.gg/gwsSTykWbu). The problem is that I have to add every client manually to the plugin (de.sportkanone123.clientdetector.spigot.manager.ClientManager.java) that’s why your client isn’t detected. If you tell me what you changed (data send on “minecraft:brand” or your custom channel) so that the other plugins detect your client I can add it to the clients list. Another option would be that you send me your client and I test it manually and see if it’s detectable. ~Sportkanone123

So users can add custom detection configuration?
