### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player" is null

### ISSUE THREAD

**Issue by maiminhdung** [Sportkanone123/ClientDetector#15]
Error: https://pastebin.com/81fDEq7J
Info:
Version server: Pearl 1.18.2
Java 17
I'm using Fabric to join server
Plugin version 2.5-EXPERIMENTAL

**To Reproduce**
When player joined server and the error plugin show up

**Comment by Loving11ish** [comment]
Hi, this bug is also affecting my paper/waterfall network running 1.19.  The exception is also throwing a Via plugin error too, I'm guessing you hook into their API's.

Please see the pastebin link for my error.

https://pastebin.com/465niRuQ

Hope this also helps

I am connecting using vanilla with optifine on 1.19.

Using 2.5-EXPERIMENTAL
Java 17

**Comment by Sportkanone123** [comment]
Should be fixed with commit 3995cc385a1bddb897959fe7bf9c35e9edbcb791.
~Sportkanone123
